# Author: Jose Angel Garcia Gomez
# Date: 04/04/2023
# Description: Dockerfile for node-express-docker

version: '3'
services:
  node-express-docker:
    environment:
      - NODE_ENV=develpment
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    container_name: node-express-docker
    expose:
      - 4000
    ports:
      - "4000:4000"
    command: npm start